---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/harvesting-validator
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/harvesting-validator
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/harvesting-validator
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/harvesting-validator
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: iE+PfHBV2lbVz7ZM5gh+mxvIlUxprV76IMCQ12FGdCvUtbcqyWbNbw==
---
kind: secret
name: docker_password
data: MuK6t/gIDFjFtR1tPGNktF+YucJ+UcodL6hgrAbhheMkk/r42nekTxU/zudjxUU2CUio0CazhfkHenSJFxpg8w==
---
kind: signature
hmac: 582b7e75b9bb64f396277430a8e133b1a99a0689290fc9036d44d4ef45745ffa

...
