steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: lblod/harvesting-validator
      tags: "${CI_COMMIT_TAG##v}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: tag
    ref: refs/tags/v*
